### ISSUE TITLE
create docker container registry

### ISSUE THREAD

**Issue by niyawe** [RoboCupAtHome/Simulation-OPL-TiaGO#2]
As Etienne mentioned in the telegram group, we need a docker container registry (here on github, on dockerhub, ...), where the built images can be uploaded to.

Afterwards we have to change https://github.com/RoboCupAtHome/Simulation-OPL-TiaGO/blob/main/docker-compose.tiago.yml#L15

Optionally we can automatically build images via github actions.

**Comment by EtienneSchmitz** [comment]
You can inspire by this workflow if you want to push on github registry : https://github.com/EtienneSchmitz/ros-devcontainer-vscode/tree/master/.github/workflows. 
You need to change only this line : https://github.com/EtienneSchmitz/ros-devcontainer-vscode/blob/31b6a82b5fc5cee504ae1ef4d81dbc2f5beecf5a/.github/workflows/docker-publish.yml#L18

**Comment by EtienneSchmitz** [comment]
I will handle it tommorow !

**Comment by niyawe** [comment]
https://github.com/RoboCupAtHome/Simulation-OPL-TiaGO/pkgs/container/simulation-opl-tiago
